name: Build Application

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip --verbose
        pip install telethon cryptg pillow pyinstaller --verbose
        
    - name: Build Windows
      shell: bash
      run: |
        pyinstaller --name TeleSpam --onefile --noconsole --clean src/TeleSpam.py --debug all
      
    - name: List directory
      run: |
        dir /s
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: TeleSpam-Windows
        path: dist/TeleSpam.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip --verbose
        pip install telethon cryptg pillow pyinstaller --verbose
        brew install python-tk

    - name: Build macOS
      run: |
        pyinstaller --name TeleSpam --onefile --noconsole --clean src/TeleSpam.py --debug all
        
    - name: List directory
      run: |
        ls -la
        ls -la dist
        
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: TeleSpam-macOS
        path: dist/TeleSpam.app